"""Finalize columns

Revision ID: 365fda0c5abc
Revises: 870145392315
Create Date: 2023-11-15 21:00:38.557547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365fda0c5abc'
down_revision: Union[str, None] = '870145392315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock_time_options', sa.Column('clock_time', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clock_time_options', 'clock_time')
    # ### end Alembic commands ###
