"""Finalize columns

Revision ID: f1d62b3e4d07
Revises: d160a53763d9
Create Date: 2023-11-15 20:32:24.639904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d62b3e4d07'
down_revision: Union[str, None] = 'd160a53763d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock_time_options', sa.Column('raw_measure_column_value', sa.Numeric(), nullable=False))
    op.add_column('clock_time_options', sa.Column('measure_column_value_for_clock', sa.Numeric(), nullable=False))
    op.add_column('clock_time_options', sa.Column('dataset_name', sa.String(), nullable=False))
    op.add_column('clock_time_options', sa.Column('prompt_template', sa.String(), nullable=True))
    op.drop_column('clock_time_options', 'prompt')
    op.drop_column('clock_time_options', 'measure_column_value')
    op.drop_column('clock_time_options', 'clock_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock_time_options', sa.Column('clock_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clock_time_options', sa.Column('measure_column_value', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('clock_time_options', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clock_time_options', 'prompt_template')
    op.drop_column('clock_time_options', 'dataset_name')
    op.drop_column('clock_time_options', 'measure_column_value_for_clock')
    op.drop_column('clock_time_options', 'raw_measure_column_value')
    # ### end Alembic commands ###
