"""Finalize columns

Revision ID: 870145392315
Revises: f1d62b3e4d07
Create Date: 2023-11-15 20:35:01.258034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870145392315'
down_revision: Union[str, None] = 'f1d62b3e4d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock_time_options', sa.Column('prompt', sa.String(), nullable=True))
    op.drop_column('clock_time_options', 'prompt_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clock_time_options', sa.Column('prompt_template', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clock_time_options', 'prompt')
    # ### end Alembic commands ###
